apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: okteto.dev/java-maven-backendReactive:1.2.2-SNAPSHOT
          name: backendReactive

---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  ports:
    - name: "backend"
      port: 8081
  selector:
    app: backend

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  annotations:
    dev.okteto.com/generate-host: backend
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: backend
                port:
                  number: 8081
            path: /
            pathType: ImplementationSpecific
