name: backendReactive
services:
  backendReactive:
    public: true
    image: okteto.dev/java-maven-backendReactive:1.2.2-SNAPSHOT
    build: .
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: 100m
      memory: 128Mi
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - 27017
    resources:
      cpu: 100m
      memory: 128Mi
    volumes:
      - /bitnami/mongodb
  deploy:
    - name: Deploy backend
    - command: kubectl apply -f k8s.yml
  dev:
    backendReactive:
      image: okteto/maven:3
      command: bash
      sync:
        - .:/usr/src/app
      forward:
        - 5005:5005
      volumes:
        - /root/.m2